// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2jm2qJqSJg0fJr8E5iHlVI7vetashpMk',
    appId: '1:931581618112:web:b1568ef228ac664fc98a25',
    messagingSenderId: '931581618112',
    projectId: 'portafolio-3d703',
    authDomain: 'portafolio-3d703.firebaseapp.com',
    storageBucket: 'portafolio-3d703.firebasestorage.app',
    measurementId: 'G-MD2M0YJDVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVfKvLf9K-B4wvcNneZHE2qVxeIp6ks4',
    appId: '1:931581618112:android:564fe16636fab30cc98a25',
    messagingSenderId: '931581618112',
    projectId: 'portafolio-3d703',
    storageBucket: 'portafolio-3d703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMw7IorNoacf1mdKnnSU4L8jVD6pHikKg',
    appId: '1:931581618112:ios:20437e16d7e646ddc98a25',
    messagingSenderId: '931581618112',
    projectId: 'portafolio-3d703',
    storageBucket: 'portafolio-3d703.firebasestorage.app',
    iosBundleId: 'com.example.portafolioWebapp2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMw7IorNoacf1mdKnnSU4L8jVD6pHikKg',
    appId: '1:931581618112:ios:20437e16d7e646ddc98a25',
    messagingSenderId: '931581618112',
    projectId: 'portafolio-3d703',
    storageBucket: 'portafolio-3d703.firebasestorage.app',
    iosBundleId: 'com.example.portafolioWebapp2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2jm2qJqSJg0fJr8E5iHlVI7vetashpMk',
    appId: '1:931581618112:web:d00447c9730e0066c98a25',
    messagingSenderId: '931581618112',
    projectId: 'portafolio-3d703',
    authDomain: 'portafolio-3d703.firebaseapp.com',
    storageBucket: 'portafolio-3d703.firebasestorage.app',
    measurementId: 'G-J41XD4V9B9',
  );
}
